### ISSUE TITLE
Support for PyPy

### ISSUE THREAD

**Issue by nbgl** [n1analytics/anonlink#167]
We are currently not supporting PyPy. Maybe this should change.

We support the latest version of Python and the one before that. Right now this means 3.7 and 3.6.

The newest version PyPy supports is 3.5. We have three options:
- Officially give up supporting PyPy;
- Maintain status quo: PyPy is an optional test, support is half-considered in design decisions, but we don't make an active effort; and
- Fix PyPy support, revert back to using only Python 3.5 features, and make PyPy a required test.

Thoughts, @hardbyte?

Aha! Link: https://csiro.aha.io/features/ANONLINK-57

**Comment by hardbyte** [comment]
Tongue in cheek option:
- help PyPy move to Python 3.7

**Comment by nbgl** [comment]
Since no action is required, I am closing this issue.
