### ISSUE TITLE
Tests shouldn't be pinned to specific machines

### ISSUE THREAD

**Issue by wilko77** [n1analytics/anonlink#46]
The tests are pinned to specific machines in the jenkinsfile:
```
def configs = [		    
     [label: 'GPU 1', pythons: ['python3.4', 'python3.5', 'python3.6'], compilers: ['clang', 'gcc']],
     [label: 'McNode', pythons: ['python3.5'], compilers: ['clang', 'gcc']]
 ]
```

This should be replaced with more generic labels, e.g. `osx` for `McNode`.

The problem is, that if one of those nodes goes down, the tests will fail. It renders the redundancy in the jenkins nodes useless.

**Comment by hardbyte** [comment]
This is done - although the *Release* stage is still pinned to a specific computer for reproducibility.
